### ISSUE TITLE
Make reservations possible

### ISSUE THREAD

**Issue by hgrecco** [studo-app/campus-qr#102]
Is there a way to allow users to make a reservation for a specific date (or range of dates) and time, and select a group of persons to authorize them?

**Comment by vonox7** [comment]
Yes, reservations are possible within the *Access control* submenu, see the following screenshot. All reservations can then be viewed on https://campus-qr-domain/admin/access/export. Only users with the *Access management & guest check-in* role are allowed to create such authorisations.
![image](https://user-images.githubusercontent.com/621501/131223732-f7b4fb0d-996c-48e6-a46a-8f2c07a85136.png)
