### ISSUE TITLE
Error 500 if visit request receives no location, but location has seats defined

### ISSUE THREAD

**Issue by pbek** [studo-app/campus-qr#34]
You will get an error 500 (log says `java.lang.IllegalArgumentException: No seat provided but location has seats defined`) if a visit POST request without the seat number is made, but the location has seats defined.

e.g.
- <https://server/location/c65200af79517a925d44/visit> results in error 500
- <https://server/location/c65200af79517a925d44-1/visit> results in `ok`

I guess it would be better to catch the exception and use another status code with an error message.
There also is an error 500 if a seat is defined in the request but the location has no seats.

(@euneuber, in case you want to watch)

**Comment by vonox7** [comment]
@pbek You are right. Throwing on those client argument exceptions a `BadRequestException` instead of an `IllegalArgumentException` would lead Ktor to respond with a HTTP 400 instead of a HTTP 500, which would be more appropriate for this case. Do you want to check all 33 occurrences of an `IllegalArgumentException` and replace them with a `BadRequestException` (if appropriate in this case) and create a pull request for that?

**Comment by pbek** [comment]
> and create a pull request for that?

That's still in discussion. 😆

**Comment by euneuber** [comment]
In my humble opinion, it is simple:
**500** - server did something wrong
**400** - client did something wrong

**Comment by vonox7** [comment]
Fixed by https://github.com/studo-app/campus-qr/pull/39 , https://github.com/studo-app/campus-qr/commit/8c2553ea818c51769f138e85fc3932454b0a2a58 and https://github.com/studo-app/campus-qr/commit/1d69fb4f6f72f1eb5f87d241b62db8291c08f1d0

**Comment by pbek** [comment]
Awesome, thank you. I'll take a look on Monday!

**Comment by pbek** [comment]
@vonox7, I can confirm that now you get an error 400, but the user still has no clue what happened. 😞 
On the server there now is a `io.ktor.features.BadRequestException: No seat provided but location has seats defined`.

**Comment by pbek** [comment]
I created a new issue https://github.com/studo-app/campus-qr/issues/46.
