### ISSUE TITLE
Poor documentation of shared key feature

### ISSUE THREAD

**Issue by functionaldude** [studo-app/campus-qr#49]
We need better docs for the **API Access** feature, and how to use the *X-Authorization* header.

**Comment by functionaldude** [comment]
https://github.com/studo-app/campus-qr/pull/48

**Comment by pbek** [comment]
@functionaldude, this doesn't seem to work for me:

## On server

```bash
> mongo "mongodb://user:pass@localhost:27017/campus-qr" --eval 'db.configurations.find({_id: "authSharedSecret"})'
MongoDB shell version v4.4.1
<snip>
MongoDB server version: 4.4.1
{ "_id" : "authSharedSecret", "stringValue" : "", "intValue" : null, "value" : "our-long-secret" }
```

looks fine, `our-long-secret`

## On client

```bash
> curl 'https://our-host/location/list' -H 'X-Authorization: our-long-secret'
forbidden^J
```

Says `forbidden`. Note that this request works when I use `SESSION_CAMPUS_QR` cookie instead of `X-Authorization`.

**Comment by pbek** [comment]
I made a new issue #50.
