### ISSUE TITLE
Don't output checkInDate in listActiveCheckIns API as float

### ISSUE THREAD

**Issue by pbek** [studo-app/campus-qr#53]
When using the `listActiveCheckIns` API the `checkInDate` is returned as a float with an exponent. It would be better to use a unix timestamp or even better an ISO 8601 date.

## Example

```
[{"id":"4e286aed66e200221c61a13262de0b4d","locationId":"c65200af79517a925d45","locationName":"Besprechungsraum 1","seat":17,"checkInDate":1.60214467586E12}]
```

@euneuber (in case you want to watch)

**Comment by pbek** [comment]
`1.60214467586E12` converted to integer would represented as something like `52739-12-12T03:44:20+00:00` if it would be a unix timestamp.

**Comment by functionaldude** [comment]
I did some small investigation, so `1.60214467586E12` should be `Thu Oct 08 10:11:15 CEST 2020` if you treat it as JS timestamp which are always expressed in milliseconds. Can it be that you treat them as seconds?

**Comment by pbek** [comment]
Dividing by 1000 and casting to int to get a timestamp works, thank you,
