### ISSUE TITLE
Refused to load the script 'http://127.0.0.1:8070/admin/campusqr-admin.js'

### ISSUE THREAD

**Issue by bahaa-kallas** [studo-app/campus-qr#6]
Using the default PORT and HOST. browser unable to load moderatorFrontend js bundle file.
console error:
```
Refused to load the script 'http://127.0.0.1:8070/admin/campusqr-admin.js' because it violates the following Content Security
Policy directive: "script-src 'self'". Note that 'script-src-elem' was not explicitly set, so 'script-src' is used as a fallback.
```
the error has to do with this header 
https://github.com/studo-app/campus-qr/blob/6275c0616b3302c7c0c97c357f1bd567f52c4ff6/src/serverMain/kotlin/com/studo/campusqr/Server.kt#L46

as temporary solution I commented out this line

**Comment by functionaldude** [comment]
Default host is now `0.0.0.0`.

**Comment by bahaa-kallas** [comment]
@functionaldude does changing the default host will solve it ? did you checked ? Because I checked and still can't fetch the bundle file and the same console error is shown

**Comment by ffactory-ofcl** [comment]
https://github.com/studo-app/campus-qr/pull/18 fixes this. It's because the script tag loads from `$baseUrl/static` when it should be loading from `/static`

**Comment by ffactory-ofcl** [comment]
Easiest solution until #18 gets merged is to access it via localhost:8070 instead of 127.0.0.1:8070

**Comment by vonox7** [comment]
This is very strange. The current master works for me (on chrome & firefox) with `127.0.0.1:8070`, but when i would access the site on `localhost:8070` i get the policy error
