### ISSUE TITLE
Empty pages when printing QR codes using the small template

### ISSUE THREAD

**Issue by lazka** [studo-app/campus-qr#70]
* Enable small pages
* Create a location with seats
* Select "Print / download QR code"
* Print the page (to a pdf file for example)

**Excepted:** Every page shows two QR codes

**Actual:** Every second page is completely empty

Browser: Firefox 82, Commit: 49f8e627a27a4c90

Example PDF printed with Firefox attached:

[small.pdf](https://github.com/studo-app/campus-qr/files/5493634/small.pdf)

The large template works better, though there is **one** empty page at the end, which isn't that bad imo:

[large.pdf](https://github.com/studo-app/campus-qr/files/5493644/large.pdf)

**Comment by vonox7** [comment]
Hi, what operating system are you using? The font rendering looks pretty different, therefore the spacing is also different. I guess the Tahoma font isn't installed on your device - could you inspect which sans-serif fallback font is used? It's not Tahoma and also not Arial (e.g. the Q letter looks different).

**Comment by vonox7** [comment]
Closed due to no response.
