### ISSUE TITLE
CSV export broken when data contains ";"

### ISSUE THREAD

**Issue by lazka** [studo-app/campus-qr#71]
* Create a location with a name containing ";"
* Create a checkin for that location
* Create a report for that user
* Select "Export all check-ins of the infected person via Excel .csv file"

Expected:

CSV can be opened with LibreOffice/Excel

Actual:

Due to missing escaping the column count for that row containing the ";" is wrong.

Example output:

```
sep=;
someone@example.at;30.11.2020 16:40:33;Location with CSV problems '",;,"'*#@öäü;-
someone@example.at;25.11.2020 12:48:58;Test Location;-
someone@example.at;25.11.2020 12:48:49;Test Location;-
someone@example.at;25.11.2020 12:45:57;Test Location;-
```

**Comment by lazka** [comment]
I'll create a PR for this later

**Comment by vonox7** [comment]
Nice, thanks!

**Comment by vonox7** [comment]
@euneuber fixed the issue, thanks for that! 👍
