### ISSUE TITLE
Exportables

### ISSUE THREAD

**Issue by ns327** [studo-app/campus-qr#73]
How can the " check-ins from specific people can be downloaded as csv file to open them in Excel." feature be used? I cannot find any menu regarding this.

**Comment by vonox7** [comment]
Via the corresponding export button. You need to have permissions to trace infections to do that. 
![image](https://user-images.githubusercontent.com/621501/105712220-cb9fca00-5f19-11eb-87c1-aea188a46577.png)
See https://github.com/studo-app/campus-qr :)
BR
