### ISSUE TITLE
Please remove JCenter from build dependencies (because it closes down)

### ISSUE THREAD

**Issue by euneuber** [studo-app/campus-qr#75]
News is from https://www.infoq.com/news/2021/02/jfrog-jcenter-bintray-closure/

Please replace JCenter to avoid possible disruption on building...

**Comment by vonox7** [comment]
Thanks for the info, will be done as soon as verified that all dependencies are also on mavenCentral.

**Comment by vonox7** [comment]
Current blocker: https://github.com/Kotlin/kotlinx.html/issues/173 / https://github.com/Kotlin/kotlinx.html/issues/81

According to JFrog, builds will work until Jan 2022. Neverless, migration will be done as soon as all blockers are migrated off JCenter.

**Comment by vonox7** [comment]
Fixed by https://github.com/studo-app/campus-qr/pull/82
