### ISSUE TITLE
Unable to Deploy on Scalingo

### ISSUE THREAD

**Issue by disintegr8te** [studo-app/campus-qr#97]
Hi,
after the App is deployed an Login is not Possible. 
The Moderator Login Forms opens but an Login isnt Possible the Message "Could not establish a connection. Please ensure a good internet connection and reload the page." appears.
I suspect its because of the Port Variable. You can't define the PORT Variable in Scalingo it is always 443.

Is there maybe an need to Change the Code to use 443 for the Moderator Login?

Best Regards

**Comment by vonox7** [comment]
Hi, based on this description it is hard to debug what is happening. Please note, that at least Scalingo sets up the `PORT` environment variable automatically (it is most probably not 443, as it is the internal docker port). Maybe you did not set up the database correctly?
BR
